spring.application.name=smart-calendar-assistant

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_calendar_assistant
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false
