spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smart_calendar_assistant}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  error:
    include-message: always
